version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-testuser}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-testPassword}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data_container:
